### ISSUE TITLE
C3D visualization

### ISSUE THREAD

**Issue by AX9898** [FingerRec/3DNet_Visualization#1]
hi，I saw in the to do list that you intend to support C3D visualization in this work. Have you do it right now？

**Comment by slighting666** [comment]
@AX9898 
I meet the same problem？ do you solve it ？ can you help me？ qq：858856173

**Comment by FingerRec** [comment]
sorry for the late reply!
The C3D visualization is quite easy. I will add this asap.

**Comment by FingerRec** [comment]
Hi, @AX9898 @slighting666 , C3D is support now; Look readme for details
