### ISSUE TITLE
3D ResNet and pre-trained model

### ISSUE THREAD

**Issue by slighting666** [FingerRec/3DNet_Visualization#2]
good job！
Can you provide a code that includes 3D ResNet and a pre-trained model, directly using the two for visualization?

**Comment by FingerRec** [comment]
No Problem. I will add this asap.

**Comment by slighting666** [comment]
@FingerRec 
Do you have time to add it? Thank you!

**Comment by FingerRec** [comment]
Really sorry for the late reply!!!
I will notify you once I finish V2, in few days!

**Comment by FingerRec** [comment]
Hi, @slighting666 , I have update R3D; You may need to download pretrain R3D model from https://github.com/kenshohara/3D-ResNets-PyTorch

**Comment by slighting666** [comment]
ok thanks！ @FingerRec
